# Generated by Django 4.1.6 on 2023-03-22 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0006_donation_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.AddField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
