# Generated by Django 4.1.6 on 2023-03-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0008_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
